<a href="https://colab.research.google.com/github/drAshcroft/MAT422/blob/main/HM_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Combinations: We can create a vector space by performing a linear combination of basis vectors.  This is easy to do with numpy as it handles vectors natively.

In [1]:
import numpy as np
#Build the first Vector
u1=np.array([1,3])
u2=np.array([-3,0])

#we can combine the terms by using any linear combination of the basis vectors
a=.5
b=5
U=a*u1+b*u2
print(U)

[-14.5   1.5]


Matrix operations can be performed by using the numpy array as well, and are easily performed to get information about a matric

In [2]:
A =np.array([[1,2],[-3,7]])
print('Matrix A')
print(A)
print()
#get the column space of A
for i in range(A.shape[1]):
  print('Column Vector ' + str(i) + '=' + str(A[:,i].T))


print()
print('Linear combition of column space')
a=-.5
b=3
w= a*A[:,0] + b*A[:,1]
print(w)

Matrix A
[[ 1  2]
 [-3  7]]

Column Vector 0=[ 1 -3]
Column Vector 1=[2 7]

Linear combition of column space
[ 5.5 22.5]


In [3]:
print('We can check for linear independance of a set of vectors')
vectors=[]
vectors.append( np.array([1,0,1]))
vectors.append( np.array([1,1,1]))
vectors.append( np.array([0,0,1]))

print('With the vectors:')
for v in vectors: print(v)

print('We check for linear independance by performing checking if the projections of all the vectors is zero')
independant =True
for i in range(len(vectors)):
  for j in range(i+1,len(vectors)):
    proj = np.dot(vectors[i],vectors[j])
    if proj>0:
      print(f'Vector {i} and Vector {j} overlap by {proj}')
      independant=False
      break
if independant:
  print('Vector set is independant')
else:
  print('Vector set is not independant')

We can check for linear independance of a set of vectors
With the vectors:
[1 0 1]
[1 1 1]
[0 0 1]
We check for linear independance by performing checking if the projections of all the vectors is zero
Vector 0 and Vector 1 overlap by 2
Vector 1 and Vector 2 overlap by 1
Vector set is not independant


In [4]:
print('Performing this test again with independant vectors')
vectors=[]
vectors.append( np.array([1,0,0]))
vectors.append( np.array([0,2,0]))
vectors.append( np.array([0,0,1]))

print('With the vectors:')
for v in vectors: print(v)

print('We check for linear independance by performing checking if the projections of all the vectors is zero')
independant =True
for i in range(len(vectors)):
  for j in range(i+1,len(vectors)):
    proj = np.dot(vectors[i],vectors[j])
    if proj>0:
      print(f'Vector {i} and Vector {j} overlap by {proj}')
      independant=False
      break
if independant:
  print('Vector set is independant')
else:
  print('Vector set is not independant')

Performing this test again with independant vectors
With the vectors:
[1 0 0]
[0 2 0]
[0 0 1]
We check for linear independance by performing checking if the projections of all the vectors is zero
Vector set is independant


In [5]:
print('The computer can be used to normalize vectors quickly and easily')
for v in vectors:
  print(v/np.linalg.norm(v))

The computer can be used to normalize vectors quickly and easily
[1. 0. 0.]
[0. 1. 0.]
[0. 0. 1.]


Using a code example from
zerobone https://zerobone.net/blog/cs/gram-schmidt-orthogonalization/, we can easily use Gram-Schmidt to provide an orthonomal basis of our vectors. Which is far easier than performing these calculations with a calculator or excel.
Gram Schmid is used to convert an arbitrary basis set into an orthnomal basis for


In [6]:
def gram_schmidt(A):
    (n, m) = A.shape
    for i in range(m):
        q = A[:, i] # i-th column of A
        for j in range(i):
            q = q - np.dot(A[:, j], A[:, i]) * A[:, j]

        if np.array_equal(q, np.zeros(q.shape)):
            raise np.linalg.LinAlgError("The column vectors are not linearly independent")

        # normalize q
        q = q / np.sqrt(np.dot(q, q))

        # write the vector back in the matrix
        A[:, i] = q
    return A



#we provide a random matrix of column basis vectors.  We wish to create an orthonormal basis from this matrix to provide easier calculations in the future.
test = np.array([[3.0, 1.0], [2.0, 2.0]])
print(f"{test}\n as initial guesses for the basis")
test= gram_schmidt(test)
print(f'{test}\n is the orthomormal basis')


[[3. 1.]
 [2. 2.]]
 as initial guesses for the basis
[[ 0.83205029 -0.5547002 ]
 [ 0.5547002   0.83205029]]
 is the orthomormal basis


In [7]:
from numpy import linalg as LA

test=np.array([ [1,0,0],[0,10,0],[0,0,3]])
print(f"{test}\n as our diagonal matrix")
eigenvalues, eigenvectors = LA.eig(test)
print(f"this matrix has the eigenvalues = {eigenvalues}")
print(f'this matrix has the eigenvectors = {eigenvectors}')


[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  3]]
 as our diagonal matrix
this matrix has the eigenvalues = [ 1. 10.  3.]
this matrix has the eigenvectors = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
test=np.array([ [1,0,1],[0,10,0],[.5,0,3]])
print(f"{test}\n as our random matrix")
eigenvalues, eigenvectors = LA.eig(test)
print()
print(f"this matrix has the eigenvalues = \n{eigenvalues}")
print(f'this matrix has the eigenvectors = \n{eigenvectors}')

[[ 1.   0.   1. ]
 [ 0.  10.   0. ]
 [ 0.5  0.   3. ]]
 as our random matrix
this matrix has the eigenvalues = 
[ 0.77525513  3.22474487 10.        ]
this matrix has the eigenvectors = 
[[-0.97566304 -0.40997761  0.        ]
 [ 0.          0.          1.        ]
 [ 0.21927526 -0.91209559  0.        ]]


In [16]:
Q, R = np.linalg.qr(test)

print(f'Original Matrix\n{test}')
print(f'\nQ:{Q}\n\nR:{R}')
print()
print(f'matrix is correctly decomposed:\n err(Test-QR)= {np.sum(test-np.dot(Q,R))}')

Original Matrix
[[ 1.   0.   1. ]
 [ 0.  10.   0. ]
 [ 0.5  0.   3. ]]

Q:[[-0.89442719  0.         -0.4472136 ]
 [-0.          1.          0.        ]
 [-0.4472136   0.          0.89442719]]

R:[[-1.11803399  0.         -2.23606798]
 [ 0.         10.          0.        ]
 [ 0.          0.          2.23606798]]

matrix is correctly decomposed:
 err(Test-QR)= 7.771561172376096e-16


We can use numpy to solve system of equations and perform linear regression. First we look at just the base method.